### ISSUE TITLE
pagenationが行われてない

### ISSUE THREAD

**Issue by anatawa12** [bdunderscore/vpm-repo-list-generator#232]
これによりMA v1.0.0がレポジトリから消滅した

https://vcc.docs.vrchat.com/guides/create-listing

> Do not remove old versions of your VPM packages after publishing them. Removing old versions will break projects using [source control](https://vcc.docs.vrchat.com/vpm/source-control).

に違反してしまっている

**Comment by bdunderscore** [comment]
修正しました。ありがとうございます。
